export * from './cep'
export * from './cnpj'
export { Email } from '../../../../shared/vo/email'
export { ID } from '../../../../shared/vo/id'
export { Telefone } from '../../../../shared/vo/telefone'